import type { ClimateZone } from './visitorLocation';
import type { PlantEntry } from './seasonPlantsExtended';

type Season = 'spring' | 'summer' | 'autumn' | 'winter';

/** مراعي، حشائش علفية، أشجار حراجية — تُدمج مع قوائم الموسم */
export const PASTURE_FORESTRY: Record<ClimateZone, Record<Season, PlantEntry[]>> = {
  arid: {
    spring: [
      { ar: 'برسيم حجازي', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'برسيم مصري', en: 'Egyptian clover', de: 'Ägyptischer Klee' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'عشبة السودان', en: 'Sudan grass', de: 'Sudangras' },
      { ar: 'ذرة علفية', en: 'Fodder sorghum', de: 'Futter-Hirse' },
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'فول سوداني علف', en: 'Forage peanut', de: 'Futter-Erdnuss' },
      { ar: 'نخيل الحطب', en: 'Date palm (forage)', de: 'Dattelpalme (Futter)' },
      { ar: 'سيلوس (ذرة+برسيم)', en: 'Silage mix', de: 'Silagemischung' },
      { ar: 'ملحية', en: 'Saltbush (Atriplex)', de: 'Salzbusch' },
      { ar: 'رغل', en: 'Saltwort (Salsola)', de: 'Salsola' },
      { ar: 'حصا', en: 'Saxaul (Haloxylon)', de: 'Saxaul' },
      { ar: 'ضرم', en: 'Panicum grass', de: 'Panicum' },
      { ar: 'سذاب', en: 'Artemisia', de: 'Artemisia' },
      { ar: 'طرفا / إبل', en: 'Tamarisk', de: 'Tamarix' },
      { ar: 'سمر (طلح)', en: 'Acacia / Samr', de: 'Akazie' },
      { ar: 'غاف', en: 'Ghaf tree', de: 'Ghaf-Baum' },
      { ar: 'سدر / زيزفون', en: 'Lote tree (Ziziphus)', de: 'Jujube-Baum' },
      { ar: 'عرعر', en: 'Juniper', de: 'Wacholder' },
      { ar: 'صنوبر حلبي', en: 'Aleppo pine', de: 'Aleppo-Kiefer' },
      { ar: 'أوكالبتوس', en: 'Eucalyptus', de: 'Eukalyptus' },
      { ar: 'نيم', en: 'Neem', de: 'Neem' },
      { ar: 'أركان', en: 'Argan', de: 'Argan' },
      { ar: 'زيتون بري', en: 'Wild olive', de: 'Wildolive' },
      { ar: 'بلوط سوري', en: 'Syrian oak', de: 'Syrischer Eiche' },
      { ar: 'حور', en: 'Poplar', de: 'Pappel' },
      { ar: 'صفصاف', en: 'Willow', de: 'Weide' },
      { ar: 'توت بري', en: 'Wild mulberry', de: 'Wild-Maulbeere' },
      { ar: 'قيقب', en: 'Maple', de: 'Ahorn' },
    ],
    summer: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'عشبة السودان', en: 'Sudan grass', de: 'Sudangras' },
      { ar: 'ذرة علفية', en: 'Fodder sorghum', de: 'Futter-Hirse' },
      { ar: 'دوار الشمس علف', en: 'Sunflower forage', de: 'Sonnenblume Futter' },
      { ar: 'فول سوداني علف', en: 'Forage peanut', de: 'Futter-Erdnuss' },
      { ar: 'ملحية', en: 'Saltbush', de: 'Salzbusch' },
      { ar: 'رغل', en: 'Saltwort', de: 'Salsola' },
      { ar: 'حصا', en: 'Saxaul', de: 'Saxaul' },
      { ar: 'ضرم', en: 'Panicum', de: 'Panicum' },
      { ar: 'سذاب', en: 'Artemisia', de: 'Artemisia' },
      { ar: 'طرفا', en: 'Tamarisk', de: 'Tamarix' },
      { ar: 'سمر', en: 'Acacia', de: 'Akazie' },
      { ar: 'غاف', en: 'Ghaf', de: 'Ghaf' },
      { ar: 'نخيل', en: 'Date palm', de: 'Dattelpalme' },
      { ar: 'أوكالبتوس', en: 'Eucalyptus', de: 'Eukalyptus' },
      { ar: 'نيم', en: 'Neem', de: 'Neem' },
      { ar: 'أركان', en: 'Argan', de: 'Argan' },
      { ar: 'صبار التين الشوكي (علف)', en: 'Prickly pear forage', de: 'Kaktusfeige Futter' },
      { ar: 'عرفج', en: 'Lemon grass (Cymbopogon)', de: 'Zitronengras' },
    ],
    autumn: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'قمح علف', en: 'Fodder wheat', de: 'Futterweizen' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'فول علف', en: 'Fodder vetch', de: 'Futter-Wicke' },
      { ar: 'طرفا', en: 'Tamarisk', de: 'Tamarix' },
      { ar: 'سمر', en: 'Acacia', de: 'Akazie' },
      { ar: 'سدر', en: 'Lote tree', de: 'Jujube' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
      { ar: 'حور', en: 'Poplar', de: 'Pappel' },
      { ar: 'صفصاف', en: 'Willow', de: 'Weide' },
    ],
    winter: [
      { ar: 'برسيم شتوي', en: 'Winter alfalfa', de: 'Winter-Luzerne' },
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'قمح علف', en: 'Fodder wheat', de: 'Futterweizen' },
      { ar: 'فول علف', en: 'Fodder vetch', de: 'Futter-Wicke' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'سدر', en: 'Lote tree', de: 'Jujube' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'عرعر', en: 'Juniper', de: 'Wacholder' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
      { ar: 'أركان', en: 'Argan', de: 'Argan' },
    ],
  },
  mediterranean: {
    spring: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'عشبة السودان', en: 'Sudan grass', de: 'Sudangras' },
      { ar: 'شوفان علف', en: 'Oats forage', de: 'Futterhafer' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'صنوبر حلبي', en: 'Aleppo pine', de: 'Aleppo-Kiefer' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
      { ar: 'حور', en: 'Poplar', de: 'Pappel' },
      { ar: 'صفصاف', en: 'Willow', de: 'Weide' },
      { ar: 'توت', en: 'Mulberry', de: 'Maulbeere' },
      { ar: 'سدر', en: 'Lote tree', de: 'Jujube' },
      { ar: 'طرفا', en: 'Tamarisk', de: 'Tamarix' },
    ],
    summer: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'ذرة علفية', en: 'Fodder sorghum', de: 'Futter-Hirse' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
      { ar: 'أوكالبتوس', en: 'Eucalyptus', de: 'Eukalyptus' },
      { ar: 'نيم', en: 'Neem', de: 'Neem' },
    ],
    autumn: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
    ],
    winter: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
    ],
  },
  subtropical: {
    spring: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'نيم', en: 'Neem', de: 'Neem' },
      { ar: 'أوكالبتوس', en: 'Eucalyptus', de: 'Eukalyptus' },
    ],
    summer: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'عشبة السودان', en: 'Sudan grass', de: 'Sudangras' },
      { ar: 'نيم', en: 'Neem', de: 'Neem' },
    ],
    autumn: [{ ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' }],
    winter: [{ ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' }],
  },
  tropical: {
    spring: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'عشبة النجيل', en: 'Napier grass', de: 'Elefantengras' },
      { ar: 'موز علف', en: 'Banana forage', de: 'Bananen-Futter' },
    ],
    summer: [
      { ar: 'عشبة النجيل', en: 'Napier grass', de: 'Elefantengras' },
      { ar: 'عشبة السودان', en: 'Sudan grass', de: 'Sudangras' },
    ],
    autumn: [{ ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' }],
    winter: [{ ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' }],
  },
  temperate: {
    spring: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'شوفان علف', en: 'Oats forage', de: 'Futterhafer' },
      { ar: 'صفصاف', en: 'Willow', de: 'Weide' },
      { ar: 'حور', en: 'Poplar', de: 'Pappel' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
    ],
    summer: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
    ],
    autumn: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'بلوط', en: 'Oak', de: 'Eiche' },
    ],
    winter: [
      { ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
    ],
  },
  cold: {
    spring: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'شوفان علف', en: 'Oats forage', de: 'Futterhafer' },
      { ar: 'صفصاف', en: 'Willow', de: 'Weide' },
      { ar: 'صنوبر', en: 'Pine', de: 'Kiefer' },
    ],
    summer: [
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'حلفا', en: 'Rhodes grass', de: 'Rhodesgras' },
    ],
    autumn: [{ ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' }],
    winter: [{ ar: 'شعير علف', en: 'Fodder barley', de: 'Futtergerste' }],
  },
};
