import type { LangKey } from './appData';
import type { ClimateZone } from './visitorLocation';

export type PlantEntry = Record<LangKey, string>;

type Season = 'spring' | 'summer' | 'autumn' | 'winter';

/** موسّعة — تشمل محاصيل، طبية، زينة، ونباتات قد تكون مقيدة قانونياً (للإرشاد فقط) */
export const EXTENDED_PLANTS: Record<ClimateZone, Record<Season, PlantEntry[]>> = {
  arid: {
    spring: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل حلو', en: 'Bell pepper', de: 'Paprika' },
      { ar: 'فلفل حار', en: 'Chili pepper', de: 'Chili' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'فاصوليا خضراء', en: 'Green beans', de: 'Grüne Bohnen' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'ذرة حلوة', en: 'Sweet corn', de: 'Süßmais' },
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'جرجير', en: 'Arugula', de: 'Rucola' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' },
      { ar: 'لفت', en: 'Turnip', de: 'Rübe' },
      { ar: 'كرفس', en: 'Celery', de: 'Sellerie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'ريحان', en: 'Basil', de: 'Basilikum' },
      { ar: 'زعتر', en: 'Thyme', de: 'Thymian' },
      { ar: 'إكليل الجبل', en: 'Rosemary', de: 'Rosmarin' },
      { ar: 'مريمية', en: 'Sage', de: 'Salbei' },
      { ar: 'زعفران (بصل)', en: 'Saffron corms', de: 'Safran-Knollen' },
      { ar: 'بابريكا', en: 'Paprika', de: 'Paprika' },
      { ar: 'بامية (شتلات)', en: 'Okra seedlings', de: 'Okra-Setzlinge' },
      { ar: 'بطيخ (شتلات)', en: 'Watermelon seedlings', de: 'Wassermelonen-Setzlinge' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'يقطين', en: 'Pumpkin', de: 'Kürbis' },
      { ar: 'فول', en: 'Fava beans', de: 'Ackerbohnen' },
      { ar: 'عدس', en: 'Lentils', de: 'Linsen' },
      { ar: 'حمص', en: 'Chickpeas', de: 'Kichererbsen' },
      { ar: 'قمح', en: 'Wheat', de: 'Weizen' },
      { ar: 'شعير', en: 'Barley', de: 'Gerste' },
      { ar: 'ذرة علف', en: 'Fodder corn', de: 'Futtermais' },
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'زيتون (شتلات)', en: 'Olive seedlings', de: 'Oliven-Setzlinge' },
      { ar: 'عنب (عقل)', en: 'Grape cuttings', de: 'Reben-Stecklinge' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
      { ar: 'لوز', en: 'Almond', de: 'Mandel' },
      { ar: 'خوخ', en: 'Peach', de: 'Pfirsich' },
      { ar: 'مشمش', en: 'Apricot', de: 'Aprikose' },
      { ar: 'ورد', en: 'Rose', de: 'Rose' },
      { ar: 'ياسمين', en: 'Jasmine', de: 'Jasmin' },
      { ar: 'حناء (قانوني للزينة)', en: 'Henna (ornamental)', de: 'Henna (Zier)' },
      { ar: 'الصبار الطبي', en: 'Aloe vera', de: 'Aloe vera' },
      { ar: 'حشيش (غير مسموح)', en: 'Cannabis (restricted)', de: 'Cannabis (verboten)' },
      { ar: 'خشخاش (مراقب)', en: 'Poppy (controlled)', de: 'Mohn (kontrolliert)' },
      { ar: 'تبغ (مرخّص فقط)', en: 'Tobacco (licensed only)', de: 'Tabak (nur lizenziert)' },
    ],
    summer: [
      { ar: 'ملوخية', en: 'Molokhia', de: 'Molokhia' },
      { ar: 'بامية', en: 'Okra', de: 'Okra' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'ذرة حلوة', en: 'Sweet corn', de: 'Süßmais' },
      { ar: 'فاصوليا', en: 'Beans', de: 'Bohnen' },
      { ar: 'يقطين', en: 'Pumpkin', de: 'Kürbis' },
      { ar: 'فلفل حار', en: 'Chili', de: 'Chili' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'ريحان', en: 'Basil', de: 'Basilikum' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'زعتر', en: 'Thyme', de: 'Thymian' },
      { ar: 'إكليل الجبل', en: 'Rosemary', de: 'Rosmarin' },
      { ar: 'الصبار الطبي', en: 'Aloe vera', de: 'Aloe vera' },
      { ar: 'صبار', en: 'Cactus pads', de: 'Kaktus' },
      { ar: 'سمسم', en: 'Sesame', de: 'Sesam' },
      { ar: 'دوار الشمس', en: 'Sunflower', de: 'Sonnenblume' },
      { ar: 'قطن', en: 'Cotton', de: 'Baumwolle' },
      { ar: 'ذرة علف', en: 'Fodder corn', de: 'Futtermais' },
      { ar: 'برسيم', en: 'Alfalfa', de: 'Luzerne' },
      { ar: 'نخيل (شتلات)', en: 'Date palm offshoots', de: 'Dattelpalme' },
      { ar: 'موز (شتلات)', en: 'Banana suckers', de: 'Banane' },
      { ar: 'مانجو (شتلات)', en: 'Mango seedlings', de: 'Mango' },
      { ar: 'حشيش (غير مسموح)', en: 'Cannabis (restricted)', de: 'Cannabis (verboten)' },
    ],
    autumn: [
      { ar: 'خس شتوي', en: 'Winter lettuce', de: 'Wintersalat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'جرجير', en: 'Arugula', de: 'Rucola' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'لفت', en: 'Turnip', de: 'Rübe' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'فول', en: 'Fava beans', de: 'Ackerbohnen' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'زعتر', en: 'Thyme', de: 'Thymian' },
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' },
      { ar: 'عدس', en: 'Lentils', de: 'Linsen' },
      { ar: 'حمص', en: 'Chickpeas', de: 'Kichererbsen' },
      { ar: 'قمح', en: 'Wheat', de: 'Weizen' },
      { ar: 'شعير', en: 'Barley', de: 'Gerste' },
      { ar: 'زعفران (بصل)', en: 'Saffron corms', de: 'Safran-Knollen' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
    ],
    winter: [
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'لفت', en: 'Turnip', de: 'Rübe' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'فول', en: 'Fava beans', de: 'Ackerbohnen' },
      { ar: 'عدس', en: 'Lentils', de: 'Linsen' },
      { ar: 'حمص', en: 'Chickpeas', de: 'Kichererbsen' },
      { ar: 'قمح', en: 'Wheat', de: 'Weizen' },
      { ar: 'شعير', en: 'Barley', de: 'Gerste' },
      { ar: 'زعفران', en: 'Saffron', de: 'Safran' },
      { ar: 'برتقال (شتلات)', en: 'Orange seedlings', de: 'Orangen-Setzlinge' },
      { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
    ],
  },
  mediterranean: {
    spring: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل حلو', en: 'Bell pepper', de: 'Paprika' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'فاصوليا', en: 'Beans', de: 'Bohnen' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'جرجير', en: 'Arugula', de: 'Rucola' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'ريحان', en: 'Basil', de: 'Basilikum' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'زعتر', en: 'Thyme', de: 'Thymian' },
      { ar: 'إكليل الجبل', en: 'Rosemary', de: 'Rosmarin' },
      { ar: 'زعفران', en: 'Saffron', de: 'Safran' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
      { ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' },
      { ar: 'ورد', en: 'Rose', de: 'Rose' },
      { ar: 'حشيش (غير مسموح)', en: 'Cannabis (restricted)', de: 'Cannabis (verboten)' },
    ],
    summer: [
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'بامية', en: 'Okra', de: 'Okra' },
      { ar: 'ذرة حلوة', en: 'Sweet corn', de: 'Süßmais' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'ريحان', en: 'Basil', de: 'Basilikum' },
      { ar: 'الصبار الطبي', en: 'Aloe vera', de: 'Aloe vera' },
      { ar: 'دوار الشمس', en: 'Sunflower', de: 'Sonnenblume' },
      { ar: 'يقطين', en: 'Pumpkin', de: 'Kürbis' },
      { ar: 'فلفل حار', en: 'Chili', de: 'Chili' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'خوخ', en: 'Peach', de: 'Pfirsich' },
      { ar: 'مشمش', en: 'Apricot', de: 'Aprikose' },
    ],
    autumn: [
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'لفت', en: 'Turnip', de: 'Rübe' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'فول', en: 'Fava beans', de: 'Ackerbohnen' },
      { ar: 'قمح', en: 'Wheat', de: 'Weizen' },
      { ar: 'شعير', en: 'Barley', de: 'Gerste' },
      { ar: 'عدس', en: 'Lentils', de: 'Linsen' },
      { ar: 'حمص', en: 'Chickpeas', de: 'Kichererbsen' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'تفاح (شتلات)', en: 'Apple seedlings', de: 'Apfel-Setzlinge' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
    ],
    winter: [
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'برتقال', en: 'Orange', de: 'Orange' },
      { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'كرنب', en: 'Kale', de: 'Grünkohl' },
    ],
  },
  subtropical: {
    spring: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'فاصوليا', en: 'Beans', de: 'Bohnen' },
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' },
      { ar: 'مانجو', en: 'Mango', de: 'Mango' },
      { ar: 'موز', en: 'Banana', de: 'Banane' },
      { ar: 'حشيش (غير مسموح)', en: 'Cannabis (restricted)', de: 'Cannabis (verboten)' },
    ],
    summer: [
      { ar: 'بامية', en: 'Okra', de: 'Okra' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'يقطين', en: 'Pumpkin', de: 'Kürbis' },
      { ar: 'فلفل حار', en: 'Chili', de: 'Chili' },
      { ar: 'مانجو', en: 'Mango', de: 'Mango' },
      { ar: 'أناناس', en: 'Pineapple', de: 'Ananas' },
      { ar: 'بابايا', en: 'Papaya', de: 'Papaya' },
    ],
    autumn: [
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
    ],
    winter: [
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'برتقال', en: 'Orange', de: 'Orange' },
      { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' },
      { ar: 'كرنب', en: 'Cabbage', de: 'Kohl' },
    ],
  },
  tropical: {
    spring: [
      { ar: 'فاصوليا', en: 'Beans', de: 'Bohnen' },
      { ar: 'يقطين', en: 'Pumpkin', de: 'Kürbis' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'موز', en: 'Banana', de: 'Banane' },
      { ar: 'مانجو', en: 'Mango', de: 'Mango' },
      { ar: 'أناناس', en: 'Pineapple', de: 'Ananas' },
      { ar: 'حشيش (غير مسموح)', en: 'Cannabis (restricted)', de: 'Cannabis (verboten)' },
    ],
    summer: [
      { ar: 'بامية', en: 'Okra', de: 'Okra' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'مانجو (شتلات)', en: 'Mango seedlings', de: 'Mango' },
      { ar: 'بابايا', en: 'Papaya', de: 'Papaya' },
      { ar: 'أناناس', en: 'Pineapple', de: 'Ananas' },
      { ar: 'موز', en: 'Banana', de: 'Banane' },
      { ar: 'فلفل حار', en: 'Chili', de: 'Chili' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
    ],
    autumn: [
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
    ],
    winter: [
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'كرنب', en: 'Cabbage', de: 'Kohl' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
    ],
  },
  temperate: {
    spring: [
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' },
      { ar: 'هليون', en: 'Asparagus', de: 'Spargel' },
      { ar: 'طماطم (شتلات)', en: 'Tomato seedlings', de: 'Tomaten-Setzlinge' },
    ],
    summer: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'فاصوليا', en: 'Beans', de: 'Bohnen' },
    ],
    autumn: [
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'تفاح', en: 'Apple', de: 'Apfel' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
    ],
    winter: [
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' },
    ],
  },
  cold: {
    spring: [
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'هليون', en: 'Asparagus', de: 'Spargel' },
    ],
    summer: [
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'كرفس', en: 'Celery', de: 'Sellerie' },
      { ar: 'طماطم (دفيئة)', en: 'Tomato (greenhouse)', de: 'Tomate (Gewächshaus)' },
      { ar: 'خيار (دفيئة)', en: 'Cucumber (greenhouse)', de: 'Gurke (Gewächshaus)' },
      { ar: 'توت', en: 'Berries', de: 'Beeren' },
    ],
    autumn: [
      { ar: 'بصل', en: 'Onion', de: 'Zwiebel' },
      { ar: 'ثوم', en: 'Garlic', de: 'Knoblauch' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' },
    ],
    winter: [
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' },
      { ar: 'كرنب', en: 'Kale', de: 'Grünkohl' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
    ],
  },
};

export const EXTENDED_HARVEST: Record<ClimateZone, Record<Season, PlantEntry[]>> = {
  arid: {
    spring: [
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'فجل', en: 'Radish', de: 'Rettich' },
      { ar: 'جرجير', en: 'Arugula', de: 'Rucola' },
      { ar: 'كزبرة', en: 'Coriander', de: 'Koriander' },
      { ar: 'بقدونس', en: 'Parsley', de: 'Petersilie' },
      { ar: 'شبت', en: 'Dill', de: 'Dill' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'ريحان', en: 'Basil', de: 'Basilikum' },
    ],
    summer: [
      { ar: 'خيار', en: 'Cucumber', de: 'Gurke' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'بامية', en: 'Okra', de: 'Okra' },
      { ar: 'ذرة', en: 'Corn', de: 'Mais' },
      { ar: 'نعناع', en: 'Mint', de: 'Minze' },
      { ar: 'الصبار الطبي', en: 'Aloe vera', de: 'Aloe vera' },
    ],
    autumn: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
      { ar: 'كوسا', en: 'Zucchini', de: 'Zucchini' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
    ],
    winter: [
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'قرنبيط', en: 'Cauliflower', de: 'Blumenkohl' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'بازلاء', en: 'Peas', de: 'Erbsen' },
      { ar: 'برتقال', en: 'Orange', de: 'Orange' },
      { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
    ],
  },
  mediterranean: {
    spring: [
      { ar: 'خس', en: 'Lettuce', de: 'Salat' },
      { ar: 'جرجير', en: 'Arugula', de: 'Rucola' },
      { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' },
      { ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' },
      { ar: 'هليون', en: 'Asparagus', de: 'Spargel' },
    ],
    summer: [
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'باذنجان', en: 'Eggplant', de: 'Aubergine' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'خوخ', en: 'Peach', de: 'Pfirsich' },
      { ar: 'مشمش', en: 'Apricot', de: 'Aprikose' },
      { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
      { ar: 'شمام', en: 'Melon', de: 'Melone' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
    ],
    autumn: [
      { ar: 'تفاح', en: 'Apple', de: 'Apfel' },
      { ar: 'رمان', en: 'Pomegranate', de: 'Granatapfel' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
      { ar: 'عنب', en: 'Grapes', de: 'Trauben' },
      { ar: 'تين', en: 'Fig', de: 'Feige' },
      { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
      { ar: 'فلفل', en: 'Pepper', de: 'Paprika' },
    ],
    winter: [
      { ar: 'برتقال', en: 'Orange', de: 'Orange' },
      { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' },
      { ar: 'كرنب', en: 'Cabbage', de: 'Kohl' },
      { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
      { ar: 'جزر', en: 'Carrot', de: 'Karotte' },
      { ar: 'زيتون', en: 'Olive', de: 'Olive' },
    ],
  },
  subtropical: {
    spring: [{ ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' }, { ar: 'خس', en: 'Lettuce', de: 'Salat' }],
    summer: [{ ar: 'مانجو', en: 'Mango', de: 'Mango' }, { ar: 'ذرة', en: 'Corn', de: 'Mais' }, { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' }],
    autumn: [{ ar: 'طماطم', en: 'Tomato', de: 'Tomate' }, { ar: 'عنب', en: 'Grapes', de: 'Trauben' }],
    winter: [{ ar: 'برتقال', en: 'Orange', de: 'Orange' }, { ar: 'ليمون', en: 'Lemon', de: 'Zitrone' }],
  },
  tropical: {
    spring: [{ ar: 'موز', en: 'Banana', de: 'Banane' }, { ar: 'مانجو', en: 'Mango', de: 'Mango' }],
    summer: [{ ar: 'أناناس', en: 'Pineapple', de: 'Ananas' }, { ar: 'بابايا', en: 'Papaya', de: 'Papaya' }],
    autumn: [{ ar: 'بابايا', en: 'Papaya', de: 'Papaya' }, { ar: 'موز', en: 'Banana', de: 'Banane' }],
    winter: [{ ar: 'مانجو', en: 'Mango', de: 'Mango' }, { ar: 'برتقال', en: 'Orange', de: 'Orange' }],
  },
  temperate: {
    spring: [{ ar: 'هليون', en: 'Asparagus', de: 'Spargel' }, { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' }, { ar: 'فراولة', en: 'Strawberry', de: 'Erdbeere' }],
    summer: [{ ar: 'طماطم', en: 'Tomato', de: 'Tomate' }, { ar: 'تفاح', en: 'Apple', de: 'Apfel' }, { ar: 'عنب', en: 'Grapes', de: 'Trauben' }],
    autumn: [{ ar: 'عنب', en: 'Grapes', de: 'Trauben' }, { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' }, { ar: 'تفاح', en: 'Apple', de: 'Apfel' }],
    winter: [{ ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' }, { ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' }],
  },
  cold: {
    spring: [{ ar: 'راوند', en: 'Rhubarb', de: 'Rhabarber' }, { ar: 'سبانخ', en: 'Spinach', de: 'Spinat' }],
    summer: [{ ar: 'توت', en: 'Berries', de: 'Beeren' }, { ar: 'خس', en: 'Lettuce', de: 'Salat' }],
    autumn: [{ ar: 'جزر', en: 'Carrot', de: 'Karotte' }, { ar: 'بطاطا', en: 'Potato', de: 'Kartoffel' }],
    winter: [{ ar: 'شمندر', en: 'Beetroot', de: 'Rote Bete' }, { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' }],
  },
};

/** نباتات إضافية حسب الطقس */
export const WEATHER_PLANT_BOOST: Record<string, PlantEntry> = {
  hot: { ar: 'بامية', en: 'Okra', de: 'Okra' },
  veryHot: { ar: 'بطيخ', en: 'Watermelon', de: 'Wassermelone' },
  dry: { ar: 'صبار / الصبار الطبي', en: 'Cactus / Aloe', de: 'Kaktus / Aloe' },
  humid: { ar: 'ملوخية', en: 'Molokhia', de: 'Molokhia' },
  windy: { ar: 'بصل / ثوم (منخفض)', en: 'Low onion/garlic', de: 'Niedrige Zwiebel/Knoblauch' },
  cool: { ar: 'بروكلي', en: 'Broccoli', de: 'Brokkoli' },
  cold: { ar: 'ملفوف', en: 'Cabbage', de: 'Kohl' },
  mild: { ar: 'طماطم', en: 'Tomato', de: 'Tomate' },
};
